#!/bin/bash
# Script to demonstrate braille chart rendering

echo "Braille Demo Script"
echo "==================="
echo ""
echo "This script demonstrates the braille chart rendering feature."
echo "To run the demo (when OCaml toolchain is available):"
echo ""
echo "  dune exec -- miaou.braille-demo"
echo ""
echo "Or to run tests:"
echo "  dune runtest"
echo ""
echo "The demo will show side-by-side comparisons of:"
echo "  - Sparkline charts (ASCII vs Braille)"
echo "  - Line charts (ASCII vs Braille)"
echo "  - Bar charts (ASCII vs Braille)"
echo ""
echo "Braille mode provides higher resolution by using Unicode"
echo "Braille patterns (U+2800–U+28FF) where each cell contains"
echo "a 2×4 grid of dots instead of a single character."
echo ""
echo "See docs/BRAILLE_CANVAS.md for more details."
