import { access, chmod, cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { escapeHtml, extractSnippet, loadManifest, renderSnippet } from './snippets.mjs';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dist = join(root, 'dist');

await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });
await cp(join(root, 'src'), dist, { recursive: true });

const manifest = await loadManifest(root);

async function htmlFiles(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await htmlFiles(path));
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      files.push(path);
    }
  }

  return files;
}

function webPath(path) {
  return path.replaceAll('\\', '/');
}

function relativeRoot(fromFile) {
  const rel = webPath(relative(dirname(fromFile), dist));
  return rel === '' ? '.' : rel;
}

async function addApiBanner(apiDist) {
  for (const htmlPath of await htmlFiles(apiDist)) {
    const rootHref = relativeRoot(htmlPath);
    let html = await readFile(htmlPath, 'utf8');
    html = html.replace(
      '</head>',
      `  <link rel="icon" type="image/png" href="${rootHref}/media/miaou-logo.png"/>
    <link rel="stylesheet" href="${rootHref}/api-banner.css"/>
  </head>`,
    );
    html = html.replace(
      /<body([^>]*)>/,
      `<body$1>
    <header class="api-site-header">
      <div class="api-site-inner">
        <a class="api-site-brand" href="${rootHref}/index.html"><img src="${rootHref}/media/miaou-logo.png" alt="" /><span>Miaou</span></a>
        <nav class="api-site-nav" aria-label="Main navigation">
          <a href="${rootHref}/docs/">Docs</a>
          <a href="${rootHref}/widgets/">Widgets</a>
          <a href="${rootHref}/tutorials/">Course</a>
          <a href="${rootHref}/showcase/">Showcase</a>
          <a href="${rootHref}/docs/api.html">API</a>
          <a href="https://github.com/trilitech/miaou">GitHub</a>
        </nav>
      </div>
    </header>`,
    );
    await chmod(htmlPath, 0o644);
    await writeFile(htmlPath, html);
  }
}

for (const htmlPath of await htmlFiles(dist)) {
  let html = await readFile(htmlPath, 'utf8');
  const referenced = [...html.matchAll(/<div data-snippet="([^"]+)"><\/div>/g)].map((match) => match[1]);

  for (const id of referenced) {
    const entry = manifest[id];
    if (!entry) {
      throw new Error(`Snippet ${id} is referenced by ${htmlPath} but not listed in snippets.json`);
    }

    const code = await extractSnippet(root, id, entry);
    html = html.replaceAll(
      `<div data-snippet="${escapeHtml(id)}"></div>`,
      renderSnippet(id, entry, code),
    );
  }

  await writeFile(htmlPath, html);
}

const apiDocs = join(root, '..', '_build', 'default', '_doc', '_html');
let hasApiDocs = true;
try {
  await access(apiDocs);
} catch {
  // API docs are generated by `dune build @doc`. Keep normal website builds fast
  // and copy the generated odoc output only when it already exists.
  hasApiDocs = false;
  console.log('Generated API docs not found; skipping dist/api copy.');
}

if (hasApiDocs) {
  try {
    const apiDist = join(dist, 'api');
    await cp(apiDocs, apiDist, { recursive: true });
    await addApiBanner(apiDist);
  } catch (error) {
    throw new Error(`Failed to copy or decorate generated API docs: ${error.message}`);
  }
}

console.log(`Built Miaou website into ${dist}`);
